// <auto-generated />
using System;
using FormAutomationApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormAutomationApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260313090342_InitialCreate4")]
    partial class InitialCreate4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FormAutomationApi.Model.DocumentType", b =>
                {
                    b.Property<int>("DocumentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DocumentTypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DocumentTypeId");

                    b.ToTable("documenttype", (string)null);
                });

            modelBuilder.Entity("FormAutomationApi.Model.DocumentVersion", b =>
                {
                    b.Property<int>("DocumentVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DocumentVersionId"));

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RetiredDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TemplatePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VersionLabel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DocumentVersionId");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("documentversion", (string)null);
                });

            modelBuilder.Entity("FormAutomationApi.Model.EmergencyContact", b =>
                {
                    b.Property<int>("EmergencyContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmergencyContactId"));

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IsPrimary")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EmergencyContactId");

                    b.ToTable("emergencycontact", (string)null);
                });

            modelBuilder.Entity("FormAutomationApi.Model.HipaaFamilyMember", b =>
                {
                    b.Property<int>("HipaaFamilyMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HipaaFamilyMemberId"));

                    b.Property<string>("FamilyNumberName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SignedDocumentId")
                        .HasColumnType("int");

                    b.HasKey("HipaaFamilyMemberId");

                    b.ToTable("hipaafamilymember", (string)null);
                });

            modelBuilder.Entity("FormAutomationApi.Model.InsurancePlan", b =>
                {
                    b.Property<int>("InsurancePlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InsurancePlanId"));

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("PayerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("InsurancePlanId");

                    b.ToTable("insuranceplan", (string)null);
                });

            modelBuilder.Entity("FormAutomationApi.Model.IntakePacket", b =>
                {
                    b.Property<int>("IntakePacketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IntakePacketId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PackedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("IntakePacketId");

                    b.ToTable("intakeplan", (string)null);
                });

            modelBuilder.Entity("Office", b =>
                {
                    b.Property<int>("OfficeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OfficeId"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("longtext");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("ZipCode")
                        .HasColumnType("longtext");

                    b.HasKey("OfficeId");

                    b.ToTable("office", (string)null);
                });

            modelBuilder.Entity("OfficeDocumentRequirement", b =>
                {
                    b.Property<int>("DocumentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DocumentTypeId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.HasKey("DocumentTypeId");

                    b.HasIndex("OfficeId");

                    b.ToTable("officedocumentrequirement", (string)null);
                });

            modelBuilder.Entity("Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("City")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("MaritalStatus")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("MiddleInitial")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("PhoneAlternate")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("PhonePrimary")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<byte[]>("SSN_Encrypted")
                        .HasColumnType("longblob");

                    b.Property<string>("SSN_Last4")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Sex")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("PatientId");

                    b.ToTable("patient", (string)null);
                });

            modelBuilder.Entity("PatientDemographic", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Ethnicity")
                        .HasColumnType("longtext");

                    b.Property<string>("Language")
                        .HasColumnType("longtext");

                    b.Property<string>("Race")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PatientId");

                    b.ToTable("patientdemographics", (string)null);
                });

            modelBuilder.Entity("PatientEmployment", b =>
                {
                    b.Property<int>("PatientEmploymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PatientEmploymentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmployerAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("EmployerName")
                        .HasColumnType("longtext");

                    b.Property<string>("Occupation")
                        .HasColumnType("longtext");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("PatientEmploymentId");

                    b.HasIndex("PatientId");

                    b.ToTable("patientemployment", (string)null);
                });

            modelBuilder.Entity("PatientInsurance", b =>
                {
                    b.Property<int>("PatientInsuranceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PatientInsuranceId"));

                    b.Property<string>("CoverageType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GroupNumber")
                        .HasColumnType("longtext");

                    b.Property<int?>("InsurancePlanId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MemberId")
                        .HasColumnType("longtext");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("RelationshipType")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("SubscriberDOB")
                        .HasColumnType("date");

                    b.Property<string>("SubscriberName")
                        .HasColumnType("longtext");

                    b.HasKey("PatientInsuranceId");

                    b.HasIndex("InsurancePlanId");

                    b.HasIndex("PatientId");

                    b.ToTable("patientinsurance", (string)null);
                });

            modelBuilder.Entity("PatientOffice", b =>
                {
                    b.Property<int>("PatientOfficeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PatientOfficeId"));

                    b.Property<bool?>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly?>("FirstVisitDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("PatientOfficeId");

                    b.HasIndex("OfficeId");

                    b.HasIndex("PatientId");

                    b.ToTable("patientoffice", (string)null);
                });

            modelBuilder.Entity("PatientPharmacy", b =>
                {
                    b.Property<int>("PatientPharmacyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PatientPharmacyId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PharmacyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.HasKey("PatientPharmacyId");

                    b.HasIndex("PatientId");

                    b.ToTable("patientpharamcy", (string)null);
                });

            modelBuilder.Entity("PatientProvider", b =>
                {
                    b.Property<int>("PatientProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PatientProviderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProviderType")
                        .HasColumnType("longtext");

                    b.HasKey("PatientProviderId");

                    b.HasIndex("PatientId");

                    b.ToTable("patientprovider", (string)null);
                });

            modelBuilder.Entity("SignedDocument", b =>
                {
                    b.Property<int>("SignedDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SignedDocumentId"));

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("DocumentVersionId")
                        .HasColumnType("int");

                    b.Property<int>("IntakePacketId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("Representative")
                        .HasColumnType("longtext");

                    b.Property<bool>("SignatureCaptured")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SignedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("SignedByRole")
                        .HasColumnType("longtext");

                    b.HasKey("SignedDocumentId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("IntakePacketId");

                    b.ToTable("signeddocument", (string)null);
                });

            modelBuilder.Entity("SignedDocumentResponse", b =>
                {
                    b.Property<int>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ResponseId"));

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ChoiceValue")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("DateValue")
                        .HasColumnType("date");

                    b.Property<string>("QuestionCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResponseType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SignedDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("TextValue")
                        .HasColumnType("longtext");

                    b.HasKey("ResponseId");

                    b.HasIndex("SignedDocumentId");

                    b.ToTable("signeddocumentresponse", (string)null);
                });

            modelBuilder.Entity("UnableToObtainSignature", b =>
                {
                    b.Property<int>("UnableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UnableId"));

                    b.Property<DateOnly?>("AttemptDate")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<int>("SignedDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("StaffInitials")
                        .HasColumnType("longtext");

                    b.HasKey("UnableId");

                    b.HasIndex("SignedDocumentId");

                    b.ToTable("unabletoobtainsignature", (string)null);
                });

            modelBuilder.Entity("FormAutomationApi.Model.DocumentVersion", b =>
                {
                    b.HasOne("FormAutomationApi.Model.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("OfficeDocumentRequirement", b =>
                {
                    b.HasOne("Office", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("PatientDemographic", b =>
                {
                    b.HasOne("Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientEmployment", b =>
                {
                    b.HasOne("Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientInsurance", b =>
                {
                    b.HasOne("FormAutomationApi.Model.InsurancePlan", "InsurancePlan")
                        .WithMany()
                        .HasForeignKey("InsurancePlanId");

                    b.HasOne("Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePlan");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientOffice", b =>
                {
                    b.HasOne("Office", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientPharmacy", b =>
                {
                    b.HasOne("Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientProvider", b =>
                {
                    b.HasOne("Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SignedDocument", b =>
                {
                    b.HasOne("FormAutomationApi.Model.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormAutomationApi.Model.IntakePacket", "IntakePacket")
                        .WithMany()
                        .HasForeignKey("IntakePacketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("IntakePacket");
                });

            modelBuilder.Entity("SignedDocumentResponse", b =>
                {
                    b.HasOne("SignedDocument", "SignedDocument")
                        .WithMany()
                        .HasForeignKey("SignedDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SignedDocument");
                });

            modelBuilder.Entity("UnableToObtainSignature", b =>
                {
                    b.HasOne("SignedDocument", "SignedDocument")
                        .WithMany()
                        .HasForeignKey("SignedDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SignedDocument");
                });
#pragma warning restore 612, 618
        }
    }
}
